# Generated by Django 4.2.11 on 2024-04-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagementSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustServiceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_stage', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ITStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_stage', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RDStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_stage', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_stage', models.CharField(max_length=150)),
            ],
        ),
    ]
